# trailing comma in table and multiline not allowed
# testkey10 = { a.d = 1, b = [ 2, 3 ], c = 3, }
# testkey8 = {
#    a.d = 1,
#    b = [ 2, 3 ],
#    c = 3
# }
# more invalid syntax
# dasdsadsa = aaa2121dasssss22
# dasdsadsa = 22aaa2121dasssss22
