---
name: Push to LuaRocks

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  pull_request:
  workflow_dispatch:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          template: ".github/rockspec.template"
          version: ${{ env.LUAROCKS_VERSION }}
          detailed_description: |
            Speedy toml parsing for lua, implemented in C 
            for use in hot-path or startup-time parsing of toml files.
